emissions_analytics:
  target: dev
  outputs:
    dev_local:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: dev_staging
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: EU
      threads: 4
      timeout_seconds: 300

    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: dev_staging
      keyfile: /opt/airflow/keys/gcp-keyfile.json
      location: EU
      threads: 4
      timeout_seconds: 300

    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: staging
      keyfile: /opt/airflow/keys/gcp-keyfile.json
      location: EU
      threads: 4
      timeout_seconds: 300
